using System.Collections.Generic;

namespace IkaStylist.Models
{
    static public class IkaUtil
    {
        //ギアパワーのIDをキーに名前を引ける辞書。逆引きのために作った。
        static public Dictionary<int, string> GearPowerDict = new Dictionary<int, string>(){
            { (int)GearPowerKind.None, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.None ) ) },
            { (int)GearPowerKind.DamageUp, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.DamageUp ) ) },
            { (int)GearPowerKind.DefenseUp, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.DefenseUp ) ) },
            { (int)GearPowerKind.InkSaverMain, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.InkSaverMain ) ) },
            { (int)GearPowerKind.InkSaverSub, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.InkSaverSub ) ) },
            { (int)GearPowerKind.InkRecoveryUp, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.InkRecoveryUp ) ) },
            { (int)GearPowerKind.RunSpeedUp, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.RunSpeedUp ) ) },
            { (int)GearPowerKind.SwimSpeedUp, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.SwimSpeedUp ) ) },
            { (int)GearPowerKind.SpecialChargeUp, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.SpecialChargeUp ) ) },
            { (int)GearPowerKind.SpecialDurationUp, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.SpecialDurationUp ) ) },
            { (int)GearPowerKind.QuickRespawn, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.QuickRespawn ) ) },
            { (int)GearPowerKind.SpecialSaver, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.SpecialSaver ) ) },
            { (int)GearPowerKind.QuickSuperJump, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.QuickSuperJump ) ) },
            { (int)GearPowerKind.BombRangeUp, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.BombRangeUp ) ) },
            { (int)GearPowerKind.OpeningGambit, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.OpeningGambit ) ) },
            { (int)GearPowerKind.LastDitchEffort, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.LastDitchEffort ) ) },
            { (int)GearPowerKind.Tenacity, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.Tenacity ) ) },
            { (int)GearPowerKind.Comeback, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.Comeback ) ) },
            { (int)GearPowerKind.ColdBlooded, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.ColdBlooded ) ) },
            { (int)GearPowerKind.NinjaSquid, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.NinjaSquid ) ) },
            { (int)GearPowerKind.Haunt, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.Haunt ) ) },
            { (int)GearPowerKind.Recon, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.Recon ) ) },
            { (int)GearPowerKind.BombSniffer, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.BombSniffer ) ) },
            { (int)GearPowerKind.InkResistanceUp, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.InkResistanceUp ) ) },
            { (int)GearPowerKind.StealthJump, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.StealthJump ) ) },
        };

        static public Dictionary<string, string> GearImgDict = new Dictionary<string, string>(){
        	{"スカッシュバンド","skashband"},
			{"サムライヘルメット","samuraiHead"},
			{"ダイバーゴーグル","dybergogle"},
			{"でんせつのぼうし","legend"},
			{"ヤコメッシュ","yakomesh"},
			{"スプラッシュゴーグル","supurashgogle"},
			{"チャリキング帽","charing"},
			{"パワードマスク","pwerdmask"},
			{"ショートビーニー","shortbini"},
			{"スゲ","suge"},
			{"スタジオヘッドホン","studioheadphon"},
			{"サファリハット","safarihat"},
			{"エイズリーバンダナ","eizuribandana"},
			{"ビバレッジキャップ","vivaledgecap"},
			{"ランニングバンド","runningband"},
			{"オーロラヘッドホン","auroraheadphon"},
			{"ヘッドバンド ホワイト","headbandwhite"},
			{"フグベルハット","hugubellhat"},
			{"トレジャーメット","treasuremet"},
			{"サイクルメット","cyclemet"},
			{"キャディ サンバイザー","candysunvisor"},
			{"ヒーローヘッズ レプリカ","herohead"},
			{"テンタクルズメット","tentaclesmet"},
			{"キャンプキャップ","campcap"},
			{"イカパッチン","ikapatchin"},
			{"カモメッシュ","kamomesh"},
			{"ナイトビジョン","nightvision"},
			{"ヤキフグ サンバイザー","yakihugusunvisor"},
			{"イカベーダーキャップ","ikabedacap"},
			{"ダテコンタクト","datecontact"},
			{"キャンプハット","camphat"},
			{"イカンカン クラシック","ikankanclassic"},
			{"アローバンド ホワイト","arrowbandwhite"},
			{"クロブチ レトロ","kurobutiretro"},
			{"バックワードキャップ","backwordcap"},
			{"イヤーマフ","earmahu"},
			{"2ラインメッシュ","2linemesh"},
			{"ジェットキャップ","jetcap"},
			{"イカスカルマスク","ikaskullmask"},
			{"スケボーメット","skateboardmet"},
			{"イカンカン","ikankan"},
			{"エゾッコメッシュ","ezokkomesh"},
			{"マルベッコー","marubekko"},
			{"ボンボンニット","bonbonnit"},
			{"ウーニーズBBキャップ","uniesBBcap"},
			{"テッカサイクルキャップ","tekkacyclecap"},
			{"サンサンサンバイザー","sunsunsunvisor"},
			{"タコゾネススコープ","takozonesscope"},
			{"パイロットゴーグル","pilotgogle"},
			{"バスケバンド","basketband"},
			{"イカ娘ずきん","ikagirlzukin"},
			{"ボーダービーニー","borderbini"},
			{"チドリキャップ","chidoricap"},
			{"モンゴウベレー","mongoberet"},
			{"イロメガネ","iromegane"},
			{"ロブスターブーニー","lobsterbuni"},
			{"オクタグラス","okutaglass"},
			{"バイザーメット","visormet"},
			{"タレサン18K","taresun18k"},
			{"ウインターボンボン","winterbonbon"},
			{"アローバンド ブラック","arrowbandblack"},
			{"アーマーメット レプリカ","armermet"},
			{"サッカーバンド","soccerband"},
			{"タコマスク","takomask"},
			{"イカノルディック","ikanordic"},
			{"テニスバンド","tennisband"},
			{"5パネルキャップ","5panelcap"},
			{"タイショウのはちまき","hachimaki"},
			{"フェイスゴーグル","facegogle"},
			{"アイロニックレイヤード","aironiclayerd"},
			{"アオサドーレ","aosadore"},
			{"かくれパイレーツ","kakurepirates"},
			{"カレッジスウェット ネイビー","collegeSwetNavy"},
			{"ロッケンベルグT ブラック","rokkenTblack"},
			{"イカ娘ノースリーブ","ikamusumeT"},
			{"ボーダーネイビー","borderNavy"},
			{"スタジャンロゴマシ","stajanRogomasi"},
			{"エゾッコラグラン","ezokkoraguran"},
			{"ニクショクT","nikusyokuT"},
			{"ミントT","mintT"},
			{"ヤキフグ8bit ブラック","yakihugu8bitBlack"},
			{"FCカラスミ","FCkarasumi"},
			{"ベイビークラゲシャツ","babyKurage"},
			{"チャリキングジャージ","cyarikingJersey"},
			{"レトロジャッジ","retroJudge"},
			{"オータムネル","autumnNeru"},
			{"ベクトルパターン レッド","vectorPatternRed"},
			{"レイニーブルーT","rainnyBlue"},
			{"レイヤード ブラック","layerdBlack"},
			{"イカセーラー ホワイト","ikaSailorWhite"},
			{"ギンガムチェック アカ","gingamCheckAka"},
			{"イカホワイト","ikaWhite"},
			{"バスケジャージ アウェイ","basuketJerseyAway"},
			{"パールドットT","parlDotT"},
			{"マルエリシャツ","marueriShirt"},
			{"ヤマビコT ブルー","yamabikoTBlue"},
			{"タコゾネスプロテクター","takozonesProtecter"},
			{"チョコガサネ","chocoGasane"},
			{"おどるイカアロハ","odoruIkaAroha"},
			{"グレープT","greapT"},
			{"バトロングホワイト","battleWhite"},
			{"シロシャツ","siroShirt"},
			{"スクールブレザー","schoolBlazer"},
			{"ロゴマシマシアロハ","logoMasiMasiAroha"},
			{"ロッケンベルグT ホワイト","rokkenTwhite"},
			{"フォレストダウン","forestDown"},
			{"イカノメT ブラック","ikanomeTblack"},
			{"ウーニーズBBシャツ","uniesBBshirt"},
			{"クラーゲス528","kurages528"},
			{"マリンボーダー","marinBorder"},
			{"F-190","f190"},
			{"オレンジボーダーラガー","orangeBorderRagger"},
			{"ガチガサネ","gachigasane"},
			{"カレッジスウェット グレー","collegeSwetGray"},
			{"チドリメロンT","chidoriMeronT"},
			{"ハラグロラグラン","haraguroRaguran"},
			{"マルフグT","maruhuguT"},
			{"ラインT ホワイト","lineTwhite"},
			{"ヒーロージャケット レプリカ","heroJaket"},
			{"マウンテンダウン","mauntainDown"},
			{"カモガサネ","kamogasane"},
			{"サニーオレンジT","sunnyOreange"},
			{"レタードオレンジ","retardOreange"},
			{"ウラスカジャン","urasukaJan"},
			{"サムライジャケット","samuraijaket"},
			{"アーマージャケット レプリカ","armerJaket"},
			{"ミスターベースボール","mrBaseball"},
			{"イカゴッチンベスト","ikagocchinBest"},
			{"アイロニックロング","aironicLong"},
			{"イカブラック","ikaBlack"},
			{"パイレーツボーダー","piratesBorder"},
			{"リールロールスウェット","reallrollswet"},
			{"ジップアップ グリーン","jipUpGreen"},
			{"マウンテンベリー","mountainBerry"},
			{"イカライダーWHITE","ikaRiderWhite"},
			{"トリコロールラガー","tricolorColor"},
			{"わかばイカT","wakabaIkaT"},
			{"タイショウのまえかけ","taisyoMaekake"},
			{"パワードスーツ","pawordSuit"},
			{"ボーダーホワイト","borderWhite"},
			{"イカスカジャン","ikasukaJan"},
			{"FCジャージー","FCjajy"},
			{"ジップアップ カモ","jipUpKamo"},
			{"ドカンT ブラック","dokanTblack"},
			{"レイヤード ホワイト","layerdWhite"},
			{"グリーンT","greenT"},
			{"バスケジャージ ホーム","basuketJerseyHome"},
			{"ベクトルラインガサネ","vectorLineGasane"},
			{"イカジャマイカ","ikaJyamaika"},
			{"タイシャツ","tieShirt"},
			{"フェスＴ","fesT"},
			{"イカスタンシャツ","ikastanShirt"},
			{"ハラシロラグラン","harashiroRaguran"},
			{"ベクトルパターン グレー","vectorPatternGray"},
			{"マスタードガサネ","mustardGasane"},
			{"ヤマビコボーダー","yamabikoBorder"},
			{"バニーポップ ブラック","bannyHopBlack"},
			{"ブロックストライプシャツ","blockStripeShirt"},
			{"ミックスシャツグレー","mixShirtGray"},
			{"イカバッテン マスタード","ikaBattenMustard"},
			{"カモフラパープル","kamohuraParple"},
			{"シャンブレーシャツ","syanbureShirt"},
			{"ギンガムチェック ミドリ","gingamCheckMidori"},
			{"ホッコリー ネイビー","hokkoryNavy"},
			{"イカセーラー ブルー","ikaSailorBlue"},
			{"イカライダーBLACK","ikaRiderBlack"},
			{"イカノボリベスト","ikaNoboriBest"},
			{"イカノメT ライトブルー","ikanomeTlightBlue"},
			{"よもぎポロ","yomogiporo"},
			{"イカリスウェット","ikariSwet"},
			{"テッカサイクルシャツ","tekkaCycleShirt"},
			{"アーバンベスト ナイト","arbanBestNight"},
			{"さくらエビポロ","sakuraEbiPoro"},
			{"ソウショクT","sousyokuT"},
			{"ボーダーモスグリーン","borderMosGreen"},
			{"エゾッコパーカー アズキ","ezokkoParkerAzuki"},
			{"スクールジャージー","schooljajy"},
			{"ガチホワイト","gachiWhite"},
			{"イカバッテンロング","ikabattenLong"},
			{"ヤマビコT アイボリー","yamabikoTivory"},
			{"F-010","f010"},
			{"アーバンベスト イエロー","arbanBestYellow"},
			{"ヴィンテージチェック","vintageCheck"},
			{"タコT","takoT"},
			{"カレッジラグラン","collegeRaguran"},
			{"ピンポンポロ","pingpongPoro"},
			{"ヤキフグ8bit ホワイト","yakihugu8bitWhite"},
			{"ガチブラック","gachiBlack"},
			{"レタードグリーン","retardGreen"},
			{"マウンテンオリーブ","mountainOlive"},
			{"シアンビーンズ","sianbeans"},
			{"レイニーシャボン","rainyShabon"},
			{"アケビコンフォート","akebiKonfort"},
			{"イカヤキチップ","ikaykiChip"},
			{"グリッチョ ブルー","gurittyoBlue"},
			{"スリッポン チドリ","suripponChidori"},
			{"オレンジアローズ","oreangeArrows"},
			{"シーホースHi レッド","seaHouseHIred"},
			{"パワードレッグス","powerdLegs"},
			{"アーマーブーツ レプリカ","armaerBoots"},
			{"ブルーベリーコンフォート","blueberryConfort"},
			{"スクールローファー","schoolRofa"},
			{"グリッチョ グリーン 限定版","guriccyoGreenPremire"},
			{"ベリベリホワイト","beriberiWhite"},
			{"キャンバスHi モロヘイヤ","cambusHImoroheiya"},
			{"シーホース ホワイト","seaHouseWhite"},
			{"ジョーズモカシン","joseMokashin"},
			{"トレッキングライト","trakkingLight"},
			{"ウミウシパープル","umiusiParple"},
			{"オイスタークロッグ","oisterClog"},
			{"レイニーアセロラ","rainnyAserora"},
			{"シーホースHi ゴールド","seaHouseHIgold"},
			{"タイショウのゲタ","taisyouGeta"},
			{"グリッチョ オレンジ","gurittyoOreange"},
			{"ラバーソール ホワイト","rabberSoleWhite"},
			{"イカ娘シューズ","ikamusumeShoes"},
			{"シーホース ブラックレザー","seaHouseBlackLether"},
			{"ウミウシブルー","umiushiBlue"},
			{"キャンバス クマノミ","cambusKumanomi"},
			{"シーホースHi ゾンビ","seaHouseHIzonbi"},
			{"ラバーソール ターコイズ","rabberSoleTarcoise"},
			{"ロッキンホワイト","rokkingWhite"},
			{"シーホースHi パープル","seaHouseHIparple"},
			{"サムライシューズ","samuraiShues"},
			{"トレッキングカスタム","trakkingCustom"},
			{"ホワイトアローズ","whiteArrow"},
			{"イカスミチップ","ikasumiChip"},
			{"ブラックビーンズ","blackBEans"},
			{"チョコクロッグ","chococlog"},
			{"モトクロスブーツ","motoclossBoots"},
			{"キャンバス ホワイト","cambusWhite"},
			{"タコゾネスブーツ","takozonesuBoots"},
			{"ロッキンイエロー","rokkingYellow"},
			{"ウミウシレッド","umiushiRed"},
			{"スリッポン レッド","suripponRed"},
			{"ヒーローキックス レプリカ","heroKicks"},
			{"ヌバックブーツ レッド","nubackBootsRed"},
			{"ミルキーダウンブーツ","milkyDownBoots"},
			{"シャークモカシン","sharkMokashin"},
			{"スリッポン ブルー","suripponBlue"},
			{"ピンクビーンズ","pinkBeans"},
			{"ヌバックブーツ イエロー","nubackBootsYellow"},
			{"キャンバス バナナ","cambusBanana"},
			{"シーホース イエロー","seaHouseYellow"},
			{"トレッキングプロ","trakkingPro"},
			{"ユデスパイカ","yudeSpika"},
			{"ロッキンチェリー","rokkingCherry"},
			{"ウミウシイエロー","umiushiYellow"},
			{"ベリベリレッド","beriberiRed"},
			{"キャンバスHi トマト","cambusHItomato"},
			{"レアスパイカ","rearSpiker"},
			{"モトクロス ソリッドブルー","motoclossSolidBule"},
			{"キャンバスHi マッシュルーム","cambusHImushroom"},
			{"ラバーソール チェリー","rabberSoleCherry"},
			{"レイニーモスグリーン","rainnyMosGreen"},
			{"アイスダウンブーツ","iceDownBoots"},
			{"クレイジーアローズ","crazyArrows"}
        };
    }
}
