using System;
using System.Collections.Generic;
using System.Windows.Media.Imaging;

namespace IkaStylist.Models
{
    static public class IkaUtil
    {
        static public System.Reflection.Assembly myAssembly = System.Reflection.Assembly.GetExecutingAssembly();

        //ギアパワーのIDをキーに名前を引ける辞書。逆引きのために作った。
        static public Dictionary<int, string> GearPowerDict = new Dictionary<int, string>(){
            { (int)GearPowerKind.None, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.None ) ) },
            { (int)GearPowerKind.DamageUp, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.DamageUp ) ) },
            { (int)GearPowerKind.DefenseUp, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.DefenseUp ) ) },
            { (int)GearPowerKind.InkSaverMain, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.InkSaverMain ) ) },
            { (int)GearPowerKind.InkSaverSub, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.InkSaverSub ) ) },
            { (int)GearPowerKind.InkRecoveryUp, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.InkRecoveryUp ) ) },
            { (int)GearPowerKind.RunSpeedUp, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.RunSpeedUp ) ) },
            { (int)GearPowerKind.SwimSpeedUp, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.SwimSpeedUp ) ) },
            { (int)GearPowerKind.SpecialChargeUp, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.SpecialChargeUp ) ) },
            { (int)GearPowerKind.SpecialDurationUp, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.SpecialDurationUp ) ) },
            { (int)GearPowerKind.QuickRespawn, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.QuickRespawn ) ) },
            { (int)GearPowerKind.SpecialSaver, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.SpecialSaver ) ) },
            { (int)GearPowerKind.QuickSuperJump, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.QuickSuperJump ) ) },
            { (int)GearPowerKind.BombRangeUp, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.BombRangeUp ) ) },
            { (int)GearPowerKind.OpeningGambit, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.OpeningGambit ) ) },
            { (int)GearPowerKind.LastDitchEffort, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.LastDitchEffort ) ) },
            { (int)GearPowerKind.Tenacity, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.Tenacity ) ) },
            { (int)GearPowerKind.Comeback, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.Comeback ) ) },
            { (int)GearPowerKind.ColdBlooded, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.ColdBlooded ) ) },
            { (int)GearPowerKind.NinjaSquid, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.NinjaSquid ) ) },
            { (int)GearPowerKind.Haunt, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.Haunt ) ) },
            { (int)GearPowerKind.Recon, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.Recon ) ) },
            { (int)GearPowerKind.BombSniffer, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.BombSniffer ) ) },
            { (int)GearPowerKind.InkResistanceUp, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.InkResistanceUp ) ) },
            { (int)GearPowerKind.StealthJump, EnumLiteralAttribute.GetLiteral( (GearPowerKind)( GearPowerKind.StealthJump ) ) },
        };

        static public Dictionary<string, string> GearImgDict = new Dictionary<string, string>(){
            {"スカッシュバンド","skashband"},
            {"サムライヘルメット","samuraiHead"},
            {"ダイバーゴーグル","dybergogle"},
            {"でんせつのぼうし","legend"},
            {"ヤコメッシュ","yakomesh"},
            {"スプラッシュゴーグル","supurashgogle"},
            {"チャリキング帽","charing"},
            {"パワードマスク","pwerdmask"},
            {"ショートビーニー","shortbini"},
            {"スゲ","suge"},
            {"スタジオヘッドホン","studioheadphon"},
            {"サファリハット","safarihat"},
            {"エイズリーバンダナ","eizuribandana"},
            {"ビバレッジキャップ","vivaledgecap"},
            {"ランニングバンド","runningband"},
            {"オーロラヘッドホン","auroraheadphon"},
            {"ヘッドバンド ホワイト","headbandwhite"},
            {"フグベルハット","hugubellhat"},
            {"トレジャーメット","treasuremet"},
            {"サイクルメット","cyclemet"},
            {"キャディ サンバイザー","candysunvisor"},
            {"ヒーローヘッズ レプリカ","herohead"},
            {"テンタクルズメット","tentaclesmet"},
            {"キャンプキャップ","campcap"},
            {"イカパッチン","ikapatchin"},
            {"カモメッシュ","kamomesh"},
            {"ナイトビジョン","nightvision"},
            {"ヤキフグ サンバイザー","yakihugusunvisor"},
            {"イカベーダーキャップ","ikabedacap"},
            {"ダテコンタクト","datecontact"},
            {"キャンプハット","camphat"},
            {"イカンカン クラシック","ikankanclassic"},
            {"アローバンド ホワイト","arrowbandwhite"},
            {"クロブチ レトロ","kurobutiretro"},
            {"バックワードキャップ","backwordcap"},
            {"イヤーマフ","earmahu"},
            {"2ラインメッシュ","2linemesh"},
            {"ジェットキャップ","jetcap"},
            {"イカスカルマスク","ikaskullmask"},
            {"スケボーメット","skateboardmet"},
            {"イカンカン","ikankan"},
            {"エゾッコメッシュ","ezokkomesh"},
            {"マルベッコー","marubekko"},
            {"ボンボンニット","bonbonnit"},
            {"ウーニーズBBキャップ","uniesBBcap"},
            {"テッカサイクルキャップ","tekkacyclecap"},
            {"サンサンサンバイザー","sunsunsunvisor"},
            {"タコゾネススコープ","takozonesscope"},
            {"パイロットゴーグル","pilotgogle"},
            {"バスケバンド","basketband"},
            {"イカ娘ずきん","ikagirlzukin"},
            {"ボーダービーニー","borderbini"},
            {"チドリキャップ","chidoricap"},
            {"モンゴウベレー","mongoberet"},
            {"イロメガネ","iromegane"},
            {"ロブスターブーニー","lobsterbuni"},
            {"オクタグラス","okutaglass"},
            {"バイザーメット","visormet"},
            {"タレサン18K","taresun18k"},
            {"ウインターボンボン","winterbonbon"},
            {"アローバンド ブラック","arrowbandblack"},
            {"アーマーメット レプリカ","armermet"},
            {"サッカーバンド","soccerband"},
            {"タコマスク","takomask"},
            {"イカノルディック","ikanordic"},
            {"テニスバンド","tennisband"},
            {"5パネルキャップ","5panelcap"},
            {"タイショウのはちまき","hachimaki"},
            {"フェイスゴーグル","facegogle"},
            {"アイロニックレイヤード","aironiclayerd"},
            {"アオサドーレ","aosadore"},
            {"かくれパイレーツ","kakurepirates"},
            {"カレッジスウェット ネイビー","collegeSwetNavy"},
            {"ロッケンベルグT ブラック","rokkenTblack"},
            {"イカ娘ノースリーブ","ikamusumeT"},
            {"ボーダーネイビー","borderNavy"},
            {"スタジャンロゴマシ","stajanRogomasi"},
            {"エゾッコラグラン","ezokkoraguran"},
            {"ニクショクT","nikusyokuT"},
            {"ミントT","mintT"},
            {"ヤキフグ8bit ブラック","yakihugu8bitBlack"},
            {"FCカラスミ","FCkarasumi"},
            {"ベイビークラゲシャツ","babyKurage"},
            {"チャリキングジャージ","cyarikingJersey"},
            {"レトロジャッジ","retroJudge"},
            {"オータムネル","autumnNeru"},
            {"ベクトルパターン レッド","vectorPatternRed"},
            {"レイニーブルーT","rainnyBlue"},
            {"レイヤード ブラック","layerdBlack"},
            {"イカセーラー ホワイト","ikaSailorWhite"},
            {"ギンガムチェック アカ","gingamCheckAka"},
            {"イカホワイト","ikaWhite"},
            {"バスケジャージ アウェイ","basuketJerseyAway"},
            {"パールドットT","parlDotT"},
            {"マルエリシャツ","marueriShirt"},
            {"ヤマビコT ブルー","yamabikoTBlue"},
            {"タコゾネスプロテクター","takozonesProtecter"},
            {"チョコガサネ","chocoGasane"},
            {"おどるイカアロハ","odoruIkaAroha"},
            {"グレープT","greapT"},
            {"バトロングホワイト","battleWhite"},
            {"シロシャツ","siroShirt"},
            {"スクールブレザー","schoolBlazer"},
            {"ロゴマシマシアロハ","logoMasiMasiAroha"},
            {"ロッケンベルグT ホワイト","rokkenTwhite"},
            {"フォレストダウン","forestDown"},
            {"イカノメT ブラック","ikanomeTblack"},
            {"ウーニーズBBシャツ","uniesBBshirt"},
            {"クラーゲス528","kurages528"},
            {"マリンボーダー","marinBorder"},
            {"F-190","f190"},
            {"オレンジボーダーラガー","orangeBorderRagger"},
            {"ガチガサネ","gachigasane"},
            {"カレッジスウェット グレー","collegeSwetGray"},
            {"チドリメロンT","chidoriMeronT"},
            {"ハラグロラグラン","haraguroRaguran"},
            {"マルフグT","maruhuguT"},
            {"ラインT ホワイト","lineTwhite"},
            {"ヒーロージャケット レプリカ","heroJaket"},
            {"マウンテンダウン","mauntainDown"},
            {"カモガサネ","kamogasane"},
            {"サニーオレンジT","sunnyOreange"},
            {"レタードオレンジ","retardOreange"},
            {"ウラスカジャン","urasukaJan"},
            {"サムライジャケット","samuraijaket"},
            {"アーマージャケット レプリカ","armerJaket"},
            {"ミスターベースボール","mrBaseball"},
            {"イカゴッチンベスト","ikagocchinBest"},
            {"アイロニックロング","aironicLong"},
            {"イカブラック","ikaBlack"},
            {"パイレーツボーダー","piratesBorder"},
            {"リールロールスウェット","reallrollswet"},
            {"ジップアップ グリーン","jipUpGreen"},
            {"マウンテンベリー","mountainBerry"},
            {"イカライダーWHITE","ikaRiderWhite"},
            {"トリコロールラガー","tricolorColor"},
            {"わかばイカT","wakabaIkaT"},
            {"タイショウのまえかけ","taisyoMaekake"},
            {"パワードスーツ","pawordSuit"},
            {"ボーダーホワイト","borderWhite"},
            {"イカスカジャン","ikasukaJan"},
            {"FCジャージー","FCjajy"},
            {"ジップアップ カモ","jipUpKamo"},
            {"ドカンT ブラック","dokanTblack"},
            {"レイヤード ホワイト","layerdWhite"},
            {"グリーンT","greenT"},
            {"バスケジャージ ホーム","basuketJerseyHome"},
            {"ベクトルラインガサネ","vectorLineGasane"},
            {"イカジャマイカ","ikaJyamaika"},
            {"タイシャツ","tieShirt"},
            {"フェスＴ","fesT"},
            {"イカスタンシャツ","ikastanShirt"},
            {"ハラシロラグラン","harashiroRaguran"},
            {"ベクトルパターン グレー","vectorPatternGray"},
            {"マスタードガサネ","mustardGasane"},
            {"ヤマビコボーダー","yamabikoBorder"},
            {"バニーポップ ブラック","bannyHopBlack"},
            {"ブロックストライプシャツ","blockStripeShirt"},
            {"ミックスシャツグレー","mixShirtGray"},
            {"イカバッテン マスタード","ikaBattenMustard"},
            {"カモフラパープル","kamohuraParple"},
            {"シャンブレーシャツ","syanbureShirt"},
            {"ギンガムチェック ミドリ","gingamCheckMidori"},
            {"ホッコリー ネイビー","hokkoryNavy"},
            {"イカセーラー ブルー","ikaSailorBlue"},
            {"イカライダーBLACK","ikaRiderBlack"},
            {"イカノボリベスト","ikaNoboriBest"},
            {"イカノメT ライトブルー","ikanomeTlightBlue"},
            {"よもぎポロ","yomogiporo"},
            {"イカリスウェット","ikariSwet"},
            {"テッカサイクルシャツ","tekkaCycleShirt"},
            {"アーバンベスト ナイト","arbanBestNight"},
            {"さくらエビポロ","sakuraEbiPoro"},
            {"ソウショクT","sousyokuT"},
            {"ボーダーモスグリーン","borderMosGreen"},
            {"エゾッコパーカー アズキ","ezokkoParkerAzuki"},
            {"スクールジャージー","schooljajy"},
            {"ガチホワイト","gachiWhite"},
            {"イカバッテンロング","ikabattenLong"},
            {"ヤマビコT アイボリー","yamabikoTivory"},
            {"F-010","f010"},
            {"アーバンベスト イエロー","arbanBestYellow"},
            {"ヴィンテージチェック","vintageCheck"},
            {"タコT","takoT"},
            {"カレッジラグラン","collegeRaguran"},
            {"ピンポンポロ","pingpongPoro"},
            {"ヤキフグ8bit ホワイト","yakihugu8bitWhite"},
            {"ガチブラック","gachiBlack"},
            {"レタードグリーン","retardGreen"},
            {"マウンテンオリーブ","mountainOlive"},
            {"シアンビーンズ","sianbeans"},
            {"レイニーシャボン","rainyShabon"},
            {"アケビコンフォート","akebiKonfort"},
            {"イカヤキチップ","ikaykiChip"},
            {"グリッチョ ブルー","gurittyoBlue"},
            {"スリッポン チドリ","suripponChidori"},
            {"オレンジアローズ","oreangeArrows"},
            {"シーホースHi レッド","seaHouseHIred"},
            {"パワードレッグス","powerdLegs"},
            {"アーマーブーツ レプリカ","armaerBoots"},
            {"ブルーベリーコンフォート","blueberryConfort"},
            {"スクールローファー","schoolRofa"},
            {"グリッチョ グリーン 限定版","guriccyoGreenPremire"},
            {"ベリベリホワイト","beriberiWhite"},
            {"キャンバスHi モロヘイヤ","cambusHImoroheiya"},
            {"シーホース ホワイト","seaHouseWhite"},
            {"ジョーズモカシン","joseMokashin"},
            {"トレッキングライト","trakkingLight"},
            {"ウミウシパープル","umiusiParple"},
            {"オイスタークロッグ","oisterClog"},
            {"レイニーアセロラ","rainnyAserora"},
            {"シーホースHi ゴールド","seaHouseHIgold"},
            {"タイショウのゲタ","taisyouGeta"},
            {"グリッチョ オレンジ","gurittyoOreange"},
            {"ラバーソール ホワイト","rabberSoleWhite"},
            {"イカ娘シューズ","ikamusumeShoes"},
            {"シーホース ブラックレザー","seaHouseBlackLether"},
            {"ウミウシブルー","umiushiBlue"},
            {"キャンバス クマノミ","cambusKumanomi"},
            {"シーホースHi ゾンビ","seaHouseHIzonbi"},
            {"ラバーソール ターコイズ","rabberSoleTarcoise"},
            {"ロッキンホワイト","rokkingWhite"},
            {"シーホースHi パープル","seaHouseHIparple"},
            {"サムライシューズ","samuraiShues"},
            {"トレッキングカスタム","trakkingCustom"},
            {"ホワイトアローズ","whiteArrow"},
            {"イカスミチップ","ikasumiChip"},
            {"ブラックビーンズ","blackBEans"},
            {"チョコクロッグ","chococlog"},
            {"モトクロスブーツ","motoclossBoots"},
            {"キャンバス ホワイト","cambusWhite"},
            {"タコゾネスブーツ","takozonesuBoots"},
            {"ロッキンイエロー","rokkingYellow"},
            {"ウミウシレッド","umiushiRed"},
            {"スリッポン レッド","suripponRed"},
            {"ヒーローキックス レプリカ","heroKicks"},
            {"ヌバックブーツ レッド","nubackBootsRed"},
            {"ミルキーダウンブーツ","milkyDownBoots"},
            {"シャークモカシン","sharkMokashin"},
            {"スリッポン ブルー","suripponBlue"},
            {"ピンクビーンズ","pinkBeans"},
            {"ヌバックブーツ イエロー","nubackBootsYellow"},
            {"キャンバス バナナ","cambusBanana"},
            {"シーホース イエロー","seaHouseYellow"},
            {"トレッキングプロ","trakkingPro"},
            {"ユデスパイカ","yudeSpika"},
            {"ロッキンチェリー","rokkingCherry"},
            {"ウミウシイエロー","umiushiYellow"},
            {"ベリベリレッド","beriberiRed"},
            {"キャンバスHi トマト","cambusHItomato"},
            {"レアスパイカ","rearSpiker"},
            {"モトクロス ソリッドブルー","motoclossSolidBule"},
            {"キャンバスHi マッシュルーム","cambusHImushroom"},
            {"ラバーソール チェリー","rabberSoleCherry"},
            {"レイニーモスグリーン","rainnyMosGreen"},
            {"アイスダウンブーツ","iceDownBoots"},
            {"クレイジーアローズ","crazyArrows"},
            {"フェスT","fesT"},
        };

        //ブランド.
        public static Brand[] brands = {
            new Brand("なし","None",0),                    // [ 00 ]
            new Brand("amiibo","amiibo",1),                // [ 01 ]
            new Brand("KOG","KOG",2),                      // [ 02 ]
            new Brand("アイロニック","Zink",3),            // [ 03 ]
            new Brand("アタリメイド","Cuttlegear",4),      // [ 04 ]
            new Brand("アロメ","Tentatek",5),              // [ 05 ]
            new Brand("エゾッコ","Zekko",6),               // [ 06 ]
            new Brand("クラーゲス","KrakOn",7),            // [ 07 ]
            new Brand("シグレニ","Inkline",8),             // [ 08 ]
            new Brand("ジモン","SplashMob",9),             // [ 09 ]
            new Brand("ファミ通","Famitsu",10),            // [ 10 ]
            new Brand("バトロイカ","SquidForce",11),       // [ 11 ]
            new Brand("フォーリマ","Forge",12),            // [ 12 ]
            new Brand("ホタックス","Skalop",13),           // [ 13 ]
            new Brand("ホッコリー","Firefin",14),          // [ 14 ]
            new Brand("ヤコ","Takoroka",15),               // [ 15 ]
            new Brand("ロッケンベルグ","Rockenberg",16),   // [ 16 ]            
            new Brand("侵略!イカ娘","SquidGirl",17)        // [ 17 ]
        };

        public static Dictionary<string, Brand> BrandImgDict = new Dictionary<string, Brand>()
        {
            { "スカッシュバンド", brands[3] },
            { "サムライヘルメット", brands[1] },
            { "ダイバーゴーグル", brands[12] },
            { "でんせつのぼうし", brands[4] },
            { "ヤコメッシュ", brands[15] },
            { "スプラッシュゴーグル", brands[12] },
            { "チャリキング帽", brands[5] },
            { "パワードマスク", brands[1] },
            { "ショートビーニー", brands[8] },
            { "スゲ", brands[8] },
            { "スタジオヘッドホン", brands[12] },
            { "サファリハット", brands[14] },
            { "エイズリーバンダナ", brands[7] },
            { "ビバレッジキャップ", brands[13] },
            { "ランニングバンド", brands[6] },
            { "オーロラヘッドホン", brands[12] },
            { "ヘッドバンド ホワイト", brands[11] },
            { "フグベルハット", brands[14] },
            { "トレジャーメット", brands[12] },
            { "サイクルメット", brands[13] },
            { "キャディ サンバイザー", brands[3] },
            { "ヒーローヘッズ レプリカ", brands[4] },
            { "テンタクルズメット", brands[12] },
            { "キャンプキャップ", brands[8] },
            { "イカパッチン", brands[1] },
            { "カモメッシュ", brands[14] },
            { "ナイトビジョン", brands[12] },
            { "ヤキフグ サンバイザー", brands[14] },
            { "イカベーダーキャップ", brands[13] },
            { "ダテコンタクト", brands[5] },
            { "キャンプハット", brands[8] },
            { "イカンカン クラシック", brands[13] },
            { "アローバンド ホワイト", brands[6] },
            { "クロブチ レトロ", brands[9] },
            { "バックワードキャップ", brands[6] },
            { "イヤーマフ", brands[12] },
            { "2ラインメッシュ", brands[7] },
            { "ジェットキャップ", brands[14] },
            { "イカスカルマスク", brands[12] },
            { "スケボーメット", brands[13] },
            { "イカンカン", brands[13] },
            { "エゾッコメッシュ", brands[6] },
            { "マルベッコー", brands[7] },
            { "ボンボンニット", brands[9] },
            { "ウーニーズBBキャップ", brands[13] },
            { "テッカサイクルキャップ", brands[3] },
            { "サンサンサンバイザー", brands[5] },
            { "タコゾネススコープ", brands[4] },
            { "パイロットゴーグル", brands[12] },
            { "バスケバンド", brands[3] },
            { "イカ娘ずきん", brands[17] },
            { "ボーダービーニー", brands[9] },
            { "チドリキャップ", brands[13] },
            { "モンゴウベレー", brands[12] },
            { "イロメガネ", brands[6] },
            { "ロブスターブーニー", brands[12] },
            { "オクタグラス", brands[14] },
            { "バイザーメット", brands[13] },
            { "タレサン18K", brands[16] },
            { "ウインターボンボン", brands[13] },
            { "アローバンド ブラック", brands[6] },
            { "アーマーメット レプリカ", brands[4] },
            { "サッカーバンド", brands[5] },
            { "タコマスク", brands[12] },
            { "イカノルディック", brands[13] },
            { "テニスバンド", brands[5] },
            { "5パネルキャップ", brands[6] },
            { "タイショウのはちまき", brands[10] },
            { "フェイスゴーグル", brands[12] },
            { "アイロニックレイヤード", brands[3] },
            { "アオサドーレ", brands[15] },
            { "かくれパイレーツ", brands[5] },
            { "カレッジスウェット ネイビー", brands[9] },
            { "ロッケンベルグT ブラック", brands[16] },
            { "イカ娘ノースリーブ", brands[17] },
            { "ボーダーネイビー", brands[9] },
            { "スタジャンロゴマシ", brands[6] },
            { "エゾッコラグラン", brands[6] },
            { "ニクショクT", brands[14] },
            { "ミントT", brands[13] },
            { "ヤキフグ8bit ブラック", brands[14] },
            { "FCカラスミ", brands[15] },
            { "ベイビークラゲシャツ", brands[9] },
            { "チャリキングジャージ", brands[5] },
            { "レトロジャッジ", brands[11] },
            { "オータムネル", brands[16] },
            { "ベクトルパターン レッド", brands[15] },
            { "レイニーブルーT", brands[7] },
            { "レイヤード ブラック", brands[11] },
            { "イカセーラー ホワイト", brands[12] },
            { "ギンガムチェック アカ", brands[6] },
            { "イカホワイト", brands[11] },
            { "バスケジャージ アウェイ", brands[3] },
            { "パールドットT", brands[13] },
            { "マルエリシャツ", brands[16] },
            { "ヤマビコT ブルー", brands[8] },
            { "タコゾネスプロテクター", brands[4] },
            { "チョコガサネ", brands[15] },
            { "おどるイカアロハ", brands[12] },
            { "グレープT", brands[13] },
            { "バトロングホワイト", brands[11] },
            { "シロシャツ", brands[9] },
            { "スクールブレザー", brands[1] },
            { "ロゴマシマシアロハ", brands[6] },
            { "ロッケンベルグT ホワイト", brands[16] },
            { "フォレストダウン", brands[8] },
            { "イカノメT ブラック", brands[5] },
            { "ウーニーズBBシャツ", brands[3] },
            { "クラーゲス528", brands[7] },
            { "マリンボーダー", brands[9] },
            { "F-190", brands[12] },
            { "オレンジボーダーラガー", brands[15] },
            { "ガチガサネ", brands[11] },
            { "カレッジスウェット グレー", brands[9] },
            { "チドリメロンT", brands[13] },
            { "ハラグロラグラン", brands[16] },
            { "マルフグT", brands[14] },
            { "ラインT ホワイト", brands[2] },
            { "ヒーロージャケット レプリカ", brands[4] },
            { "マウンテンダウン", brands[8] },
            { "カモガサネ", brands[11] },
            { "サニーオレンジT", brands[7] },
            { "レタードオレンジ", brands[9] },
            { "ウラスカジャン", brands[6] },
            { "サムライジャケット", brands[1] },
            { "アーマージャケット レプリカ", brands[4] },
            { "ミスターベースボール", brands[14] },
            { "イカゴッチンベスト", brands[7] },
            { "アイロニックロング", brands[3] },
            { "イカブラック", brands[11] },
            { "パイレーツボーダー", brands[9] },
            { "リールロールスウェット", brands[6] },
            { "ジップアップ グリーン", brands[14] },
            { "マウンテンベリー", brands[8] },
            { "イカライダーWHITE", brands[16] },
            { "トリコロールラガー", brands[15] },
            { "わかばイカT", brands[11] },
            { "タイショウのまえかけ", brands[10] },
            { "パワードスーツ", brands[1] },
            { "ボーダーホワイト", brands[9] },
            { "イカスカジャン", brands[6] },
            { "FCジャージー", brands[3] },
            { "ジップアップ カモ", brands[14] },
            { "ドカンT ブラック", brands[2] },
            { "レイヤード ホワイト", brands[11] },
            { "グリーンT", brands[12] },
            { "バスケジャージ ホーム", brands[3] },
            { "ベクトルラインガサネ", brands[15] },
            { "イカジャマイカ", brands[13] },
            { "タイシャツ", brands[9] },
            { "フェスＴ", brands[11] },
            { "イカスタンシャツ", brands[7] },
            { "ハラシロラグラン", brands[16] },
            { "ベクトルパターン グレー", brands[15] },
            { "マスタードガサネ", brands[11] },
            { "ヤマビコボーダー", brands[8] },
            { "バニーポップ ブラック", brands[6] },
            { "ブロックストライプシャツ", brands[9] },
            { "ミックスシャツグレー", brands[6] },
            { "イカバッテン マスタード", brands[11] },
            { "カモフラパープル", brands[15] },
            { "シャンブレーシャツ", brands[9] },
            { "ギンガムチェック ミドリ", brands[6] },
            { "ホッコリー ネイビー", brands[14] },
            { "イカセーラー ブルー", brands[12] },
            { "イカライダーBLACK", brands[16] },
            { "イカノボリベスト", brands[7] },
            { "イカノメT ライトブルー", brands[5] },
            { "よもぎポロ", brands[9] },
            { "イカリスウェット", brands[11] },
            { "テッカサイクルシャツ", brands[3] },
            { "アーバンベスト ナイト", brands[14] },
            { "さくらエビポロ", brands[9] },
            { "ソウショクT", brands[14] },
            { "ボーダーモスグリーン", brands[8] },
            { "エゾッコパーカー アズキ", brands[6] },
            { "スクールジャージー", brands[3] },
            { "ガチホワイト", brands[11] },
            { "イカバッテンロング", brands[11] },
            { "ヤマビコT アイボリー", brands[8] },
            { "F-010", brands[12] },
            { "アーバンベスト イエロー", brands[14] },
            { "ヴィンテージチェック", brands[16] },
            { "タコT", brands[4] },
            { "カレッジラグラン", brands[9] },
            { "ピンポンポロ", brands[6] },
            { "ヤキフグ8bit ホワイト", brands[14] },
            { "ガチブラック", brands[11] },
            { "レタードグリーン", brands[9] },
            { "マウンテンオリーブ", brands[8] },
            { "シアンビーンズ", brands[5] },
            { "レイニーシャボン", brands[8] },
            { "アケビコンフォート", brands[7] },
            { "イカヤキチップ", brands[16] },
            { "グリッチョ ブルー", brands[6] },
            { "スリッポン チドリ", brands[7] },
            { "オレンジアローズ", brands[15] },
            { "シーホースHi レッド", brands[3] },
            { "パワードレッグス", brands[1] },
            { "アーマーブーツ レプリカ", brands[4] },
            { "ブルーベリーコンフォート", brands[7] },
            { "スクールローファー", brands[1] },
            { "グリッチョ グリーン 限定版", brands[6] },
            { "ベリベリホワイト", brands[9] },
            { "キャンバスHi モロヘイヤ", brands[7] },
            { "シーホース ホワイト", brands[3] },
            { "ジョーズモカシン", brands[9] },
            { "トレッキングライト", brands[8] },
            { "ウミウシパープル", brands[5] },
            { "オイスタークロッグ", brands[7] },
            { "レイニーアセロラ", brands[8] },
            { "シーホースHi ゴールド", brands[3] },
            { "タイショウのゲタ", brands[10] },
            { "グリッチョ オレンジ", brands[6] },
            { "ラバーソール ホワイト", brands[16] },
            { "イカ娘シューズ", brands[17] },
            { "シーホース ブラックレザー", brands[3] },
            { "ウミウシブルー", brands[5] },
            { "キャンバス クマノミ", brands[7] },
            { "シーホースHi ゾンビ", brands[3] },
            { "ラバーソール ターコイズ", brands[16] },
            { "ロッキンホワイト", brands[16] },
            { "シーホースHi パープル", brands[3] },
            { "サムライシューズ", brands[1] },
            { "トレッキングカスタム", brands[8] },
            { "ホワイトアローズ", brands[15] },
            { "イカスミチップ", brands[16] },
            { "ブラックビーンズ", brands[5] },
            { "チョコクロッグ", brands[7] },
            { "モトクロスブーツ", brands[16] },
            { "キャンバス ホワイト", brands[7] },
            { "タコゾネスブーツ", brands[4] },
            { "ロッキンイエロー", brands[16] },
            { "ウミウシレッド", brands[5] },
            { "スリッポン レッド", brands[7] },
            { "ヒーローキックス レプリカ", brands[4] },
            { "ヌバックブーツ レッド", brands[16] },
            { "ミルキーダウンブーツ", brands[5] },
            { "シャークモカシン", brands[9] },
            { "スリッポン ブルー", brands[7] },
            { "ピンクビーンズ", brands[5] },
            { "ヌバックブーツ イエロー", brands[16] },
            { "キャンバス バナナ", brands[7] },
            { "シーホース イエロー", brands[3] },
            { "トレッキングプロ", brands[8] },
            { "ユデスパイカ", brands[15] },
            { "ロッキンチェリー", brands[16] },
            { "ウミウシイエロー", brands[5] },
            { "ベリベリレッド", brands[9] },
            { "キャンバスHi トマト", brands[7] },
            { "レアスパイカ", brands[15] },
            { "モトクロス ソリッドブルー", brands[16] },
            { "キャンバスHi マッシュルーム", brands[7] },
            { "ラバーソール チェリー", brands[16] },
            { "レイニーモスグリーン", brands[8] },
            { "アイスダウンブーツ", brands[5] },
            { "クレイジーアローズ", brands[15] },
            {"フェスT", brands[11]},
        };

        public static string[] MainOnlyGear = {
            "ボム飛距離アップ",
            "スタートダッシュ",
            "ラストスパート",
            "逆境強化",
            "カムバック",
            "マーキングガード",
            "イカニンジャ",
            "うらみ",
            "スタートレーダー",
            "ボムサーチ",
            "安全シューズ",
            "ステルスジャンプ"
        };

        public static string[] cantExchangeGear = {
            "アーマーメット",
            "でんせつのぼうし",
            "イカ娘ずきん",
            "イカ娘ノースリーブ",
            "イカ娘シューズ",
            "サムライヘルメット",
            "サムライジャケット",
            "サムライシューズ",
            "スタートレーダー",
            "イカパッチン",
            "スクールブレザー",
            "スクールローファー",
            "ヒーローヘッズ レプリカ",
            "ヒーロージャケット レプリカ",
            "ヒーローキックス レプリカ",
            "パワードマスク",
            "パワードスーツ",
            "パワードレッグス"
        };

        //******************* ギアの埋め込みデータ読み込み *******************//

        public static BitmapImage getGearBitmap(string filename)
        {
            string projectName = myAssembly.GetName().Name + ".Resources.";
            string pngFile = null;

            if (String.IsNullOrEmpty(filename) == false)
            {
                pngFile = projectName + filename + ".png";
            }
            return getBitmap(pngFile);
        }

        public static BitmapImage getGearPowerBitmap(int id)
        {
            string projectName = myAssembly.GetName().Name + ".Resources.";
            string pngFile = null;
            if (id != -1)
            {
                pngFile = projectName + EnumLiteralAttribute.GetLiteral((GearPowerImg)(id)) + "2.png";
            }
            return getBitmap(pngFile);
        }

        public static BitmapImage getBitmap(string filePath)
        {
            if (String.IsNullOrEmpty(filePath) == true)
            {
                return new BitmapImage();//何も表示しない.
            }
            System.IO.Stream resourcePath = myAssembly.GetManifestResourceStream(filePath);
            if (resourcePath == null) { return new BitmapImage(); }
            BitmapImage bitmap = new BitmapImage();
            bitmap.BeginInit();
            bitmap.StreamSource = resourcePath;
            bitmap.EndInit();
            return bitmap;
        }

        public static BitmapImage getBrandBitmapByImgName(string imgName)
        {
            if (String.IsNullOrEmpty(imgName) == true)
            {
                return new BitmapImage();//何も表示しない.
            }
            string projectName = myAssembly.GetName().Name + ".Resources.brand.";
            string pngFile = projectName + imgName + ".png";
            return getBitmap(pngFile);
        }
    }
}
